export enum ScreenMessage {
  LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL',
  LOGIN_FAILED = 'LOGIN_FAILED',
  OTP_SENT = 'OTP_SENT',
  ENTER_PASSWORD = 'ENTER_PASSWORD',
  OTP_NOT_VALID = 'OTP_NOT_VALID',
  UPDATE_PROFILE_SUCCESSFUL = 'UPDATE_PROFILE_SUCCESSFUL',
}
